version: '3'

services:
  myBlog_postgresql:
    image: postgres:12
    container_name: myBlog_postgresql
    volumes:
      - myBlog_postgresql:/var/lib/postgresql/date
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - myBlog_network


volumes:
  myBlog_postgresql:
    external: true
networks:
  myBlog_network:
    external: true