# Generated by Django 4.0.3 on 2022-03-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options_post_promote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='promote',
            field=models.BooleanField(default=False),
        ),
    ]
