# Generated by Django 4.0.3 on 2022-03-22 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'پروفایل کاربری', 'verbose_name_plural': 'پروفایل\u200cهای کاربران'},
        ),
    ]
